# Site settings
title: Ryan Hines
description: A portfolio of some of the projects I've done
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ryan Hines
user_description: I'm just a recent Computer Science graduate with a passion for software and game development. I have an affinity for solving problems and attempting to find efficient solutions. Programming is a fascination of mine, and I now consider it a lifestyle and enjoy learning and improving at it every day.
user_title: Software and Game Developer
email: ryan.hines.cs@gmail.com
github_username: hines-r

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
